# page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6504602116  # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: RMA Share is an intuitive app designed to transform your RateMyAgent reviews into stunning image effortlessly.
enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Satnam Singh
your_link: https://silverseahog.com/
your_city:
email_address:
facebook_username:
instagram_username: codetard
twitter_username: codetard
github_username: 29satnam
youtube_username:

# Feature List (Edit, add or remove features to be presented.)
features:
  - title: List Your Reviews
    description: Supply URL and list the reviews with a single tap.
    fontawesome_icon_name: thermometer-full

  - title: Generate Review Image
    description: With a single-tap, the app gets you shareable image.
    fontawesome_icon_name: calculator

  - title: Share Reviews Anywhere
    description: Share review image on Instagram, Facebook, X , Google Maps or any other social media.
    fontawesome_icon_name: star

# Theme Settings
topbar_color: "#fff"
topbar_transparency: 1.0
topbar_title_color: "#000"

cover_image: # Replace with alternative image path or image URL.
cover_overlay_color: "#ffffff"
cover_overlay_transparency: 1.0

device_color: coral # Set to: blue, black, yellow, coral or white.

body_background_color: "#F8F8F8"

link_color: "#1d63ea"

app_title_color: "#000"
app_price_color: "#000"
app_description_color: "#000"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
plugins:
  - jekyll-seo-tag
